name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  # -----------------------------------------
  # CI: Testler
  # -----------------------------------------
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Bağımlılıkları yükle
        run: pip install -r requirements.txt

      - name: Testleri çalıştır
        run: pytest -v
  # -----------------------------------------
  # Docker Image Build & Push & Scan
  # -----------------------------------------
  build_image:
    needs: ci
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: GHCR login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker image build
        run: docker build -t ghcr.io/${{ github.repository }}/myapp:latest .

      - name: Docker image push
        run: docker push ghcr.io/${{ github.repository }}/myapp:latest

      - name: Scan image for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}/myapp:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'